name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  code_quality:
    runs-on: ubuntu-latest
    name: Checks with black, isort
    container: python:3.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run script
        run: |
          pip install -r requirements.txt
          ls -la

      - name: Black check
        run:
          black --check .

      - name: Isort check
        run:
          isort --check .

  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: .

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: utility-nix
        path: src/linux
        retention-days: 1


    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: utility-win
        path: dist/windows
        retention-days: 1

